name: maplink
description: Package para conectar com a maplink (SOAP)
version: 1.0.0-dev.3
author: David Araujo <david@flutterando.com.br>
homepage: https://f-team.dev/
repository: https://github.com/davidsdearaujo/maplink

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  dartz: ^0.9.1
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.3
  mockito: ^4.1.1
