name: maplink
description: Package para conectar com a maplink (SOAP)
version: 1.0.0-dev.3
author: David Araujo <david@flutterando.com.br>
homepage: https://f-team.dev/
repository: https://github.com/davidsdearaujo/maplink

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  dartz: ^0.10.0-nullsafety.1
  http: ^0.13.1

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.2
